DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    firstname VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    url VARCHAR,
    bio VARCHAR,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
